# Try Catch

The try...catch statement is a block of statement to try and identify the error or exception to be thrown.

The **try** statement lets you test a block of code for errors.

The **catch** statement lets you handle the error.

The **throw** statement lets you create custom errors.

The **finally** statement lets you execute code, after try and catch, regardless of the result.

Example of the code:

The **try** is the block when you want to try your function or code: 

`try testingfunction()`

The **catch** block is where you handle the error: 

`catch(err) { }`

The **finally** block will executed regardless the result of the try/catch:  

`finally { }`
